### PR TITLE
remove dpde and dpdr_e -- these were only used once in Castro

### PR DESCRIPTION
**Pull request by zingale**
we can compute them as needed on the fly

### CODE REVIEW

**Comment by zingale** [comment]
this depends on https://github.com/AMReX-Astro/Castro/pull/1625

**Comment by zingale** [comment]
there are 2 problems with this:

breakout doesn't seem to define the needed derivatives to compute this as needed
polytrope has dedT = 0, which is in the denominator of the quantity we need to compute

**Comment by maxpkatz** [comment]
We should require that every network at least fills out all of the derivatives even if they're zero. We can detect that in Castro and set dpde and dpdr_e to zero accordingly.

**Comment by zingale** [comment]
agreed.  That was my plan.  I just haven't gotten back to this.

**Comment by maxpkatz** [comment]
As I was working on the Tillotson EOS I realized my comment above isn't really right. For that EOS the natural variables are (rho, e) and T isn't actually needed to evaluate the EOS. So while dP/de is a natural variable, dP/dT and de/dT are not (although an arbitrary T can be constructed). Since this is the same problem polytrope has, maybe we should just not worry about this change.

**Comment by zingale** [comment]
I agree, we can drop this change

**Pull request closed without merging**
