### PR TITLE
iso7 14/∞

### PR DESCRIPTION
**Pull request by maxpkatz**
Evaluate as much of the RHS as possible at compile time. Specifically we do not waste memory or flops on contributions to each RHS from rates that don't actually contribute.

### CODE REVIEW

**Comment by zingale** [comment]
there are some very large differences: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2020-12-19/test_react_C-iso7-VODE.html

**Comment by maxpkatz** [comment]
Unfortunately there probably would be for the same reason we saw in #457.

**Comment by maxpkatz** [comment]
To make this simpler to review I am retaining the old behavior that the esum is over NumRates terms even though most of them are zero. I will do the piece that skips the zero terms in a later PR.

**Comment by zingale** [comment]
the latest tests look much better

**Review by zingale — APPROVED** [review]

**Pull request merged**
