### PR TITLE
Do not define extra thermo components of eos_t ifndef EXTRA_THERMO

### PR DESCRIPTION
**Pull request by dwillcox**
This PR will not declare composition derivative components of `eos_t` unless `EXTRA_THERMO` is defined.

Previously, we would not yield a compiler error if we tried accessing the composition derivatives without `EXTRA_THERMO`, introducing undefined results and, when compiling with OpenMP, silent NaNs.

We should use the `eos_t.F90` here in Maestro to avoid problems like this.

This changes one instance of `if EXTRA_THERMO` to `ifdef EXTRA_THERMO` in `helmholtz/actual_eos.F90` to conform to all other ifdef statements in which `EXTRA_THERMO` appears.

### CODE REVIEW

**Comment by dwillcox** [comment]
So should I just merge this?

**Comment by maxpkatz** [comment]
I'm confused why the dpdX thing isn't causing a problem in Castro.

**Comment by dwillcox** [comment]
I'm looking at the Castro changelog and for 17.11:

>  -- we no longer get the compositional derivatives as part of the EOS                                                                                                                                                                       
>     call.  If you need this functionality, you need to set the                                                                                                                                                                              
>     preprocessor variable (in Fortran), EXTRA_THERMO

**Comment by maxpkatz** [comment]
Oh, because Castro has its own copy eos_type.f90.

**Comment by dwillcox** [comment]
In Castro's copy of eos_type.F90, those compositional derivatives are only part of eos_t if EXTRA_THERMO is defined.

**Comment by dwillcox** [comment]
Which is the same thing this PR does to the eos_type interface in Microphysics.

**Comment by zingale** [comment]
fine with me -- want me to run the test suite on it?

**Comment by maxpkatz** [comment]
Yes.

**Comment by zingale** [comment]
There are a lot of failures with this -- seems the pressure is wrong now?http://bender.astro.sunysb.edu/Microphysics/test-suite/test-suite-gfortran/

**Comment by dwillcox** [comment]
The conflict is resolved.

**Comment by dwillcox** [comment]
Thanks!

**Pull request merged**
