### PR TITLE
Convert aprox19 to C++

### PR DESCRIPTION
**Pull request by maxpkatz**
I've tested this on both test_rhs and test_react. For test_rhs, the maximum relative difference between the Fortran and C++ is O(1e-15) for the RHS, and O(1e-13) for the Jacobian. For test_react, the maximum relative difference is 1e-11 for the CPU build and 1e-4 for the GPU build. (The difference for the GPU build is of comparable magnitude to what we see for the other networks.)

### CODE REVIEW

**Comment by maxpkatz** [comment]
Note: #322 and #323 are necessary to be merged for this C++ implementation to exactly match the Fortran implementation.

**Comment by shardi2** [comment]
Mass_Fractions_plots_aprox19

**Comment by shardi2** [comment]
Mass_Fractions_plots_aprox19

**Comment by zingale** [comment]
here's the `test_react` comparison using `inputs_aprox19`

```
fcompare.gnu.ex react_aprox19_test_react.VODE react_aprox19_test_react.VODE.cxx

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_hydrogen-1                    3.642345262e-06           5.200528079e-06
 Xnew_helium-3                      3.598111692e-07            9.59496456e-06
 Xnew_helium-4                      1.614585521e-05           2.282282551e-05
 Xnew_carbon-12                     7.664953241e-07            1.09499332e-06
 Xnew_nitrogen-14                   2.528467163e-05           4.005704464e-05
 Xnew_oxygen-16                      1.06320148e-06           3.649442747e-06
 Xnew_neon-20                       1.494058308e-05            8.00590561e-05
 Xnew_magnesium-24                  1.963395941e-05           0.0002846559906
 Xnew_silicon-28                    7.393842538e-06           1.539777129e-05
 Xnew_sulfur-32                     1.672074696e-06           1.120318767e-05
 Xnew_argon-36                      7.019169906e-07           6.705066837e-06
 Xnew_calcium-40                    1.767443775e-06           9.667781146e-06
 Xnew_titanium-44                   3.625711192e-07           9.660146541e-06
 Xnew_chromium-48                   3.448750425e-07           8.866872117e-06
 Xnew_iron-52                       2.118532431e-07           5.649419817e-06
 Xnew_iron-54                       5.764659091e-06           1.358858921e-05
 Xnew_nickel-56                     5.877686613e-06           4.739295115e-05
 Xnew_neutron                       2.446707736e-07           6.524553961e-06
 Xnew_proton                        4.107064142e-07           1.095217104e-05
 Xold_hydrogen-1                                  0                         0
 Xold_helium-3                                    0                         0
 Xold_helium-4                                    0                         0
 Xold_carbon-12                                   0                         0
 Xold_nitrogen-14                                 0                         0
 Xold_oxygen-16                                   0                         0
 Xold_neon-20                                     0                         0
 Xold_magnesium-24                                0                         0
 Xold_silicon-28                                  0                         0
 Xold_sulfur-32                                   0                         0
 Xold_argon-36                                    0                         0
 Xold_calcium-40                                  0                         0
 Xold_titanium-44                                 0                         0
 Xold_chromium-48                                 0                         0
 Xold_iron-52                                     0                         0
 Xold_iron-54                                     0                         0
 Xold_nickel-56                                   0                         0
 Xold_neutron                                     0                         0
 Xold_proton                                      0                         0
 wdot_hydrogen-1                        3642.345262           3.758195304e-05
 wdot_helium-3                          359.8111692           9.594967914e-06
 wdot_helium-4                          16145.85521           4.373296342e-05
 wdot_carbon-12                         766.4953241           1.097218761e-06
 wdot_nitrogen-14                       25284.67163           4.045763649e-05
 wdot_oxygen-16                          1063.20148            3.72945121e-06
 wdot_neon-20                           14940.58308           8.283318936e-05
 wdot_magnesium-24                      19633.95941           0.0003192339349
 wdot_silicon-28                        7393.842538           1.560082705e-05
 wdot_sulfur-32                         1672.074696           1.398495367e-05
 wdot_argon-36                          701.9169906           7.738950286e-06
 wdot_calcium-40                        1767.443775           1.047340363e-05
 wdot_titanium-44                       362.5711192           9.676146147e-06
 wdot_chromium-48                       344.8750425           9.211748698e-06
 wdot_iron-52                           211.8532431           5.649419817e-06
 wdot_iron-54                           5764.659091            1.37917786e-05
 wdot_nickel-56                         5877.686613           6.793421463e-05
 wdot_neutron                           244.6707736           7.581036921e-06
 wdot_proton                            410.7064142           1.497467573e-05
 rho_Hnuc                           1.159870035e+31           2.464746202e-05
```

**Comment by zingale** [comment]
Here's the burn_cell output with:

```
  X1  = 0.7d0
  X2  = 0.025d0
  X3  = 0.2d0
  X4  = 0.025d0
  X5  = 0.025d0
  X6  = 0.025d0
  X7  = 0.0d0
  X8  = 0.0d0
  X9  = 0.0d0
  X10 = 0.0d0
  X11 = 0.0d0
  X12 = 0.0d0
  X13 = 0.0d0
  X14 = 0.0d0
  X15 = 0.0d0
  X16 = 0.0d0
  X17 = 0.0d0
  X18 = 0.0d0
  X19 = 0.0d0
```

and `tmax    = 0.01`

aprox19_he4

**Pull request merged**
