### PR TITLE
move the check that the temperature is reasonable after we update thermo

### PR DESCRIPTION
**Pull request by zingale**
previously, we were checking on the old T, not the T corresponding to the
current e that we are trying to integrate with.

### CODE REVIEW

**Comment by zingale** [comment]
this "fixes" the FPE we see in the test suite for the massive star problem with NSE.

But I am not 100% certain that our VODE logic will reject the step in this case.

**Comment by zingale** [comment]
actually, since we have the burn_state in vode_dvstep.H, I think I should put a step rejection if T > MAX_TEMP.  Then I think this will pick up on that.

**Comment by maxpkatz** [comment]
Yes I agree that there is potentially still an issue to be solved in making sure the step gets rejected, however this is a clearly correct change when viewed in isolation so we should still do this.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-06-07-002/index.html

**Review by maxpkatz — APPROVED** [review]

**Comment by maxpkatz** [comment]
The test failures are because some of these tests do hit T > 1e11. So while this is fine, we may want to take some other action if we detect that we have hit MAX_TEMP. This temperature is high enough that we don't expect it to be hit during a normal burn.

**Comment by zingale** [comment]
interestingly, for  test_react_C-aprox19-VODE, we trigger the temperature check 2 times with this change, and in both cases, it is because the temperature is too cold, not to hot.

**Comment by zingale** [comment]
with iso7, we have a few instances of temperature floor and about 2 dozen T > MAX_TEMP cases.

**Pull request merged**
