### PR TITLE
Introduce some optimizations to Helmholtz

### PR DESCRIPTION
**Pull request by maxpkatz**
- Remove some unnecessary calculations, e.g. ones that are not ever used or that are just zero.

- Add xne, xnp, pele, ppos, etaele to EXTRA_THERMO

### CODE REVIEW

**Comment by zingale** [comment]
eta is needed for the conductivities

**Comment by maxpkatz** [comment]
Where?

**Comment by zingale** [comment]
https://github.com/starkiller-astro/Microphysics/blob/master/conductivity/stellar/stellar_conductivity.f90

**Comment by zingale** [comment]
pele too

**Comment by zingale** [comment]
:soccer:

**Comment by dwillcox** [comment]
:sports_medal:

**Comment by maxpkatz** [comment]
Closing because this will be supplanted by other Helmholtz changes I will issue a PR for.

**Pull request closed without merging**
