### PR TITLE
Merge weaklib interface into development

### PR DESCRIPTION
**Pull request by dwillcox**
This PR merges the weaklib EOS interface into the development branch, now that Thornado, Weaklib, and the EOS/Opacity tables are publicly available.

Thornado public repository (BSD-3): https://github.com/endeve/thornado

Weaklib public repository (BSD-3): https://github.com/starkiller-astro/weaklib

EOS/Opacity tables repository (license unknown): https://code.ornl.gov/m2o/thornado-tables

Not yet ready to merge. We will need to:

- [ ] Document the weaklib interface #198 
- [ ] Add weaklib regression tests to the test suite #199 
- more?

### CODE REVIEW

**Comment by jaharris87** [comment]
Future location of weaklib tables: https://code.ornl.gov/astro/weaklib-tables

**Comment by dwillcox** [comment]
Ah, great, thanks @jaharris87!

**Comment by zingale** [comment]
is this still desired?  We would want to convert these routines to C++

**Comment by zingale** [comment]
do we still want to do this?

**Pull request closed without merging**
