### PR TITLE
Convert rprox to C++

### PR DESCRIPTION
**Pull request by maxpkatz**

### CODE REVIEW

**Comment by shardi2** [comment]
Mass_Fractions_plots_rprox

**Comment by shardi2** [comment]
Mass_Fractions_plots_rprox

**Comment by shardi2** [comment]
Mass_Fractions_plots_rprox

**Comment by zingale** [comment]
test_rhs:
```
$ fcompare.gnu.ex react_rprox_test_rhs.VODE.cxx react_rprox_test_rhs.VODE.fortran

            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Ydot_carbon-12                                   0                         0
 Ydot_oxygen-14                                   0                         0
 Ydot_oxygen-15                                   0                         0
 Ydot_oxygen-16                                   0                         0
 Ydot_flourine-17                                 0                         0
 Ydot_magnesium-22                                0                         0
 Ydot_sulfur-30                                   0                         0
 Ydot_nickel-56                                   0                         0
 Ydot_helium-4                                    0                         0
 Ydot_hydrogen-1                                  0                         0
 Xold_carbon-12                                   0                         0
 Xold_oxygen-14                                   0                         0
 Xold_oxygen-15                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_flourine-17                                 0                         0
 Xold_magnesium-22                                0                         0
 Xold_sulfur-30                                   0                         0
 Xold_nickel-56                                   0                         0
 Xold_helium-4                                    0                         0
 Xold_hydrogen-1                                  0                         0
 Tdot                                       2015232           1.218477028e-14
 Edot                                             0                         0
 J_carbon-12_carbon-12                            0                         0
 J_oxygen-14_carbon-12                            0                         0
 J_oxygen-15_carbon-12                            0                         0
 J_oxygen-16_carbon-12                            0                         0
 J_flourine-17_carbon-12                          0                         0
 J_magnesium-22_carbon-12                         0                         0
 J_sulfur-30_carbon-12                            0                         0
 J_nickel-56_carbon-12                            0                         0
 J_helium-4_carbon-12                             0                         0
 J_hydrogen-1_carbon-12                           0                         0
 J_T_carbon-12                             52428800           5.864769931e-15
 J_E_carbon-12                                    0                         0
 J_carbon-12_oxygen-14                            0                         0
 J_oxygen-14_oxygen-14                            0                         0
 J_oxygen-15_oxygen-14                            0                         0
 J_oxygen-16_oxygen-14                            0                         0
 J_flourine-17_oxygen-14                          0                         0
 J_magnesium-22_oxygen-14                         0                         0
 J_sulfur-30_oxygen-14                            0                         0
 J_nickel-56_oxygen-14                            0                         0
 J_helium-4_oxygen-14                             0                         0
 J_hydrogen-1_oxygen-14                           0                         0
 J_T_oxygen-14                             75497472           9.939364702e-15
 J_E_oxygen-14                                    0                         0
 J_carbon-12_oxygen-15                            0                         0
 J_oxygen-14_oxygen-15                            0                         0
 J_oxygen-15_oxygen-15                            0                         0
 J_oxygen-16_oxygen-15                            0                         0
 J_flourine-17_oxygen-15                          0                         0
 J_magnesium-22_oxygen-15                         0                         0
 J_sulfur-30_oxygen-15                            0                         0
 J_nickel-56_oxygen-15                            0                         0
 J_helium-4_oxygen-15                             0                         0
 J_hydrogen-1_oxygen-15                           0                         0
 J_T_oxygen-15                               303104           7.064999641e-15
 J_E_oxygen-15                                    0                         0
 J_carbon-12_oxygen-16                            0                         0
 J_oxygen-14_oxygen-16                            0                         0
 J_oxygen-15_oxygen-16                            0                         0
 J_oxygen-16_oxygen-16                            0                         0
 J_flourine-17_oxygen-16                          0                         0
 J_magnesium-22_oxygen-16                         0                         0
 J_sulfur-30_oxygen-16                            0                         0
 J_nickel-56_oxygen-16                            0                         0
 J_helium-4_oxygen-16                             0                         0
 J_hydrogen-1_oxygen-16                           0                         0
 J_T_oxygen-16                              1441792           9.000997315e-15
 J_E_oxygen-16                                    0                         0
 J_carbon-12_flourine-17                          0                         0
 J_oxygen-14_flourine-17                          0                         0
 J_oxygen-15_flourine-17                          0                         0
 J_oxygen-16_flourine-17                          0                         0
 J_flourine-17_flourine-17                         0                         0
 J_magnesium-22_flourine-17                         0                         0
 J_sulfur-30_flourine-17                          0                         0
 J_nickel-56_flourine-17                          0                         0
 J_helium-4_flourine-17                           0                         0
 J_hydrogen-1_flourine-17                         0                         0
 J_T_flourine-17                          889192448           2.731017138e-14
 J_E_flourine-17                                  0                         0
 J_carbon-12_magnesium-22                         0                         0
 J_oxygen-14_magnesium-22                         0                         0
 J_oxygen-15_magnesium-22                         0                         0
 J_oxygen-16_magnesium-22                         0                         0
 J_flourine-17_magnesium-22                         0                         0
 J_magnesium-22_magnesium-22                         0                         0
 J_sulfur-30_magnesium-22                         0                         0
 J_nickel-56_magnesium-22                         0                         0
 J_helium-4_magnesium-22                          0                         0
 J_hydrogen-1_magnesium-22                         0                         0
 J_T_magnesium-22                        2751463424           1.006931875e-14
 J_E_magnesium-22                                 0                         0
 J_carbon-12_sulfur-30                            0                         0
 J_oxygen-14_sulfur-30                            0                         0
 J_oxygen-15_sulfur-30                            0                         0
 J_oxygen-16_sulfur-30                            0                         0
 J_flourine-17_sulfur-30                          0                         0
 J_magnesium-22_sulfur-30                         0                         0
 J_sulfur-30_sulfur-30                            0                         0
 J_nickel-56_sulfur-30                            0                         0
 J_helium-4_sulfur-30                             0                         0
 J_hydrogen-1_sulfur-30                           0                         0
 J_T_sulfur-30                            402653184           1.001017327e-14
 J_E_sulfur-30                                    0                         0
 J_carbon-12_nickel-56                            0                         0
 J_oxygen-14_nickel-56                            0                         0
 J_oxygen-15_nickel-56                            0                         0
 J_oxygen-16_nickel-56                            0                         0
 J_flourine-17_nickel-56                          0                         0
 J_magnesium-22_nickel-56                         0                         0
 J_sulfur-30_nickel-56                            0                         0
 J_nickel-56_nickel-56                            0                         0
 J_helium-4_nickel-56                             0                         0
 J_hydrogen-1_nickel-56                           0                         0
 J_T_nickel-56                                    0                         0
 J_E_nickel-56                                    0                         0
 J_carbon-12_helium-4                             0                         0
 J_oxygen-14_helium-4                             0                         0
 J_oxygen-15_helium-4                             0                         0
 J_oxygen-16_helium-4                             0                         0
 J_flourine-17_helium-4                           0                         0
 J_magnesium-22_helium-4                          0                         0
 J_sulfur-30_helium-4                             0                         0
 J_nickel-56_helium-4                             0                         0
 J_helium-4_helium-4                              0                         0
 J_hydrogen-1_helium-4                            0                         0
 J_T_helium-4                              71303168           9.098802832e-15
 J_E_helium-4                                     0                         0
 J_carbon-12_hydrogen-1                           0                         0
 J_oxygen-14_hydrogen-1                           0                         0
 J_oxygen-15_hydrogen-1                           0                         0
 J_oxygen-16_hydrogen-1                           0                         0
 J_flourine-17_hydrogen-1                         0                         0
 J_magnesium-22_hydrogen-1                         0                         0
 J_sulfur-30_hydrogen-1                           0                         0
 J_nickel-56_hydrogen-1                           0                         0
 J_helium-4_hydrogen-1                            0                         0
 J_hydrogen-1_hydrogen-1                          0                         0
 J_T_hydrogen-1                            21102592           1.275044055e-14
 J_E_hydrogen-1                                   0                         0
 J_carbon-12_T                                    0                         0
 J_oxygen-14_T                                    0                         0
 J_oxygen-15_T                                    0                         0
 J_oxygen-16_T                                    0                         0
 J_flourine-17_T                                  0                         0
 J_magnesium-22_T                                 0                         0
 J_sulfur-30_T                                    0                         0
 J_nickel-56_T                                    0                         0
 J_helium-4_T                                     0                         0
 J_hydrogen-1_T                                   0                         0
 J_T_T                                      7340032           9.885487616e-15
 J_E_T                                            0                         0
 J_carbon-12_E                                    0                         0
 J_oxygen-14_E                                    0                         0
 J_oxygen-15_E                                    0                         0
 J_oxygen-16_E                                    0                         0
 J_flourine-17_E                                  0                         0
 J_magnesium-22_E                                 0                         0
 J_sulfur-30_E                                    0                         0
 J_nickel-56_E                                    0                         0
 J_helium-4_E                                     0                         0
 J_hydrogen-1_E                                   0                         0
 J_T_E                                            0                         0
 J_E_E                                            0                         0
```

**Comment by zingale** [comment]
I get some divergence when I plot this:

rprox_h1

I initialized things as:

```
  X1  = 0.001d0
  X2  = 0.01d0
  X3  = 0.01d0
  X4  = 0.001d0
  X5  = 0.001d0
  X6  = 0.001d0
  X7  = 0.001d0
  X8  = 0.001d0
  X9  = 0.274d0
  X10 = 0.7d0 
```

**Comment by zingale** [comment]
this may just be the accumulation of integration error.  If I look at a shorter time range, then things look better

**Comment by zingale** [comment]
test_react comparison:
```
            variable name            absolute error            relative error
                                        (||A - B||)         (||A - B||/||A||)
 ----------------------------------------------------------------------------
 level = 0
 density                                          0                         0
 temperature                                      0                         0
 Xnew_carbon-12                     6.288872726e-11           7.187284973e-10
 Xnew_oxygen-14                      1.23673026e-09           6.524203735e-09
 Xnew_oxygen-15                     4.298877053e-11            4.89330044e-10
 Xnew_oxygen-16                     5.188816182e-10           1.637075705e-09
 Xnew_flourine-17                   7.482744702e-10           8.509596105e-09
 Xnew_magnesium-22                  7.354664933e-10           4.170971287e-09
 Xnew_sulfur-30                     3.224668449e-11           3.683562559e-10
 Xnew_nickel-56                     3.224650408e-11           3.685314293e-10
 Xnew_helium-4                      2.056096543e-10           2.570113139e-10
 Xnew_hydrogen-1                    9.471984308e-10           1.183998053e-09
 Xold_carbon-12                                   0                         0
 Xold_oxygen-14                                   0                         0
 Xold_oxygen-15                                   0                         0
 Xold_oxygen-16                                   0                         0
 Xold_flourine-17                                 0                         0
 Xold_magnesium-22                                0                         0
 Xold_sulfur-30                                   0                         0
 Xold_nickel-56                                   0                         0
 Xold_helium-4                                    0                         0
 Xold_hydrogen-1                                  0                         0
 wdot_carbon-12                       6.2888721e-05           7.187282402e-10
 wdot_oxygen-14                      0.001236730259           1.211763838e-08
 wdot_oxygen-15                     4.298877053e-05           2.426825903e-08
 wdot_oxygen-16                      0.000518881614           2.261351695e-09
 wdot_flourine-17                   0.0007482744695           8.599648497e-09
 wdot_magnesium-22                  0.0007354664922           6.450516621e-09
 wdot_sulfur-30                     3.224668449e-05           7.657422815e-07
 wdot_nickel-56                     3.224650408e-05            0.002960848363
 wdot_helium-4                      0.0002056096528           4.478092931e-09
 wdot_hydrogen-1                    0.0009471984304           5.779355281e-08
 rho_Hnuc                           3.133675025e+21           1.649116917e-08
```

**Comment by maxpkatz** [comment]
This no longer matches Fortran since screening was added a couple months ago -- I need to go back and get that in sync.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
screening was added to the C++

**Pull request merged**
