### PR TITLE
Various optimizations to the Helmholtz EOS

### PR DESCRIPTION
**Pull request by maxpkatz**

### CODE REVIEW

**Comment by maxpkatz** [comment]
Ready for review. Main changes were:
- Cleaning out some dead code paths (compiler may have already been optimizing these out)
- Replacing a number of divides with multiplications
- Combining some of the EOS tables for improved memory access patterns

**Comment by maxpkatz** [comment]
For the wdmerger 2D collision test, this yields about a 3% performance improvement for a run with hydro and gravity.

**Comment by maxpkatz** [comment]
In my testing, the diffs for pressure and temperature are a hard zero, but the velocities have a small but non-zero difference. Not sure if that is an error or just numerical roundoff.

**Comment by zingale** [comment]
I'll run the suite on this

**Comment by dwillcox** [comment]
From Max:

>#145 is bad and I don't want to merge it

**Pull request closed without merging**
