### PR TITLE
Update extern_probin.template

### PR DESCRIPTION
**Pull request by ChrisDeGrendele**
These were never updated either. See PR #380

### CODE REVIEW

**Comment by maxpkatz** [comment]
Does this test currently work? We don't often exercise it (though I did look at it a bit when I did the C++ port).

**Comment by zingale** [comment]
oh... now I understand things.  We are still using the version of the script in `AMREX_HOME/Tools/F_scripts/`:
```
$(MICROPHYSICS_AUTO_SOURCE_DIR)/extern.F90: $(EXTERN_PARAMETERS) $(EXTERN_TEMPLATE)
	@if [ ! -d $(MICROPHYSICS_AUTO_SOURCE_DIR) ]; then mkdir -p $(MICROPHYSICS_AUTO_SOURCE_DIR); fi
	$(AMREX_HOME)/Tools/F_scripts/write_probin.py \
           -t $(EXTERN_TEMPLATE) -o $(MICROPHYSICS_AUTO_SOURCE_DIR)/extern.F90 -n extern \
           --cxx_prefix $(MICROPHYSICS_AUTO_SOURCE_DIR)/extern \
           --pa "$(EXTERN_PARAMETERS)" $(MANAGED_PROBIN_FLAG)
```
but we should switch over to the version in `Microphysics/util/build_scripts/`

In fact, Castro and MAESTROeX have already switched over to that.

**Comment by zingale** [comment]
I'm not sure what "test" you mean, but the extern parameter stuff does work for unit tests.  I'm realizing that there is some redundancy in our build system stuff that I will try to clean up shortly.

**Comment by ChrisDeGrendele** [comment]
Ah, that makes sense now. @zingale

**Comment by maxpkatz** [comment]
> I'm not sure what "test" you mean

The unit test that is being edited here (the standalone cuVODE driver).

**Comment by zingale** [comment]
oh, indeed, I have no idea about that test.

**Comment by zingale** [comment]
I don't think this is relevant anymore

**Pull request closed without merging**
