### PR TITLE
since we've merged the c12ag rates, modify the test_aprox_rates function calls

### PR DESCRIPTION
**Pull request by zingale**
this also now builds C++ only

### CODE REVIEW

**Comment by zingale** [comment]
test: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-06-19-002/test_aprox_rates_C.html

I don't understand why the original rate is different now :/

**Comment by maxpkatz** [comment]
This test evaluates for multiple values of rho and T. Your change needs to be reset before the next call to the original rate.

**Comment by maxpkatz** [comment]
That said, this would only work in serial execution, it wouldn't work in parallel. So maybe we need an optional argument to the rate routine to override.

**Comment by zingale** [comment]
this passes now:
http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-06-20/index.html

I've split the alternate c12ag rate off into it's own kernel so we don't have to worry about a race condition.

**Review by maxpkatz — APPROVED** [review]

**Pull request merged**
