### PR TITLE
aprox19 1/∞

### PR DESCRIPTION
**Pull request by maxpkatz**
Move identical particle factors into rates

### CODE REVIEW

**Comment by maxpkatz** [comment]
Note to self for later: the number of particles consumed in the proton-proton reaction is 3 even though the term goes as Y(H1)**2. This will require the same kind of special handling as the silicon burning reaction in iso7 where 7 alphas are consumed even though the term goes as Y(He4).

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-02-18-004/index.html

**Comment by zingale** [comment]
I think those errors look reasonable

**Comment by zingale** [comment]
why does the pp consume 3?  is it merging p+p and the d+p?

**Comment by maxpkatz** [comment]
Yes, that's right.

I really want it to be the case that we define an RHS term as -N * Y**N, so that the number of particles you consume is exactly the same as the exponent on Y in the term. Almost every term meets that requirement trivially with N == 1, but then there are exceptions like this one that do not. So I think what I will do (assuming no objections) is to make this the case and then multiply or divide the rate by the corresponding factors of Y to offset this. It will make the refactor in iso7 #20 even simpler.

**Comment by zingale** [comment]
or just add deuterium?

**Comment by maxpkatz** [comment]
Yes, that's also a solution, although we should make a call about how much we care about the goal of having these networks be notionally the same as the other instantiations in the literature.

**Pull request merged**
