### PR TITLE
[WIP] Merge cudadevice branch into development

### PR DESCRIPTION
**Pull request by dwillcox**
The CUDA port of VODE90 and a few networks is in a stable state. This PR is for merging this port into development.

This can't be automatically done by github so I'll work on doing this manually. If there are any issues to talk about along the way I'll update the discussion in this PR.

### CODE REVIEW

**Comment by zingale** [comment]
is this still WIP?

**Comment by dwillcox** [comment]
I still intend to do this but haven't been working on it lately.

**Comment by zingale** [comment]
why is helm_table.dat changed here?

**Comment by zingale** [comment]
this branch is stale

**Pull request closed without merging**
