### PR TITLE
Sdc fix

### PR DESCRIPTION
**Pull request by zingale**
this allows Castro to compile with SDC once again

this will close Castro issue 216

### CODE REVIEW

**Comment by zingale** [comment]
@KISSFORMISS please try the detonation with this change to see if it still behaves like it used to

**Comment by dwillcox** [comment]
I'm just looking at this and some of these changes are similar to changes I've made locally, I've pushed some additional fixes.

I am good to merge and close this PR, though I haven't tested this with Castro.

There are some other issues I've found but I'll defer them to another PR as this one is for fixing compilation issues.

**Comment by zingale** [comment]
great.  This fixes the `test_sdc` unit test now.

**Comment by zingale** [comment]
but I'm not allowed to "approve" it, since I created the original PR.

But Don's changes are good, so I will merge.

**Pull request merged**
