### PR TITLE
remove the Fortran CVODE integrator

### PR DESCRIPTION
**Pull request by zingale**
we never use it and we are not supporting Fortran integrators anymore

### CODE REVIEW

**Comment by zingale** [comment]
@dwillcox is this okay with you?

**Comment by zingale** [comment]
all tests pass: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-01-17-002/index.html

**Comment by dwillcox** [comment]
can this PR also please remove `Microphysics/unit_test/test_cvode_react`?

**Comment by zingale** [comment]
done!

**Review by dwillcox — APPROVED** [review]
Looks great!

**Pull request merged**
