### PR TITLE
aprox19 4/∞

### PR DESCRIPTION
**Pull request by maxpkatz**
Merge proton links into main reaction channels

### CODE REVIEW

**Comment by maxpkatz** [comment]
Note: this does exactly the same thing as #569, #572, and #573.

**Comment by zingale** [comment]
tests: http://groot.astro.sunysb.edu/Microphysics/test-suite/gfortran/2021-03-03-002/index.html

**Comment by zingale** [comment]
test_react_C-aprox19-VODE diffs are larger than I would have expected.

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
this looks good, I think the diffs are because there is a lot of reordering of operations now.

**Pull request merged**
