### PR TITLE
ECSN

### PR DESCRIPTION
**Pull request by sailoridy**

### CODE REVIEW

**Comment by zingale** [comment]
can you add a short description about the purpose of these changes to this github conversation so we can have the commit message be descriptive

**Comment by sailoridy** [comment]
This commit is to calculate a one-cell burn by using the ECSN networks

**Comment by maxpkatz** [comment]
Can you please change the target branch to `development` and then make sure your changes are in sync with that, if necessary?

**Comment by dwillcox** [comment]
This was merged in #173

**Pull request closed without merging**
