### PR TITLE
add the ability to boost the reaction rate

### PR DESCRIPTION
**Pull request by zingale**
add the ability to boost the reaction rates

### CODE REVIEW

**Comment by zingale** [comment]
waiting for comments before I change the other integrators

**Comment by dwillcox** [comment]
You might not be using a numerical jacobian, but if you do, its calls to `actual_rhs` should be scaled.

**Comment by dwillcox** [comment]
This looks reasonable to me though.

**Comment by maxpkatz** [comment]
Why only boost by a positive factor? One might want to slow the reactions down too. Test on react_boost > 0.

**Comment by zingale** [comment]
I'd done the rest of the burners (but not SDC yet), and I've address Max's comment about react_boost > 0.

This is ready to merge.  See: https://github.com/starkiller-astro/Microphysics/blob/development/Docs/tests/ode_scaling.ipynb for a demonstration of this method with VODE.

**Pull request merged**
